Update sign_binary

diff --git a/scripts/sign_binary b/scripts/sign_binary
--- a/scripts/sign_binary
+++ b/scripts/sign_binary
@@ -37,8 +37,7 @@ elif [[ "$unamestr" == 'Msys' ]]; then
    fi
 elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='mac'
-   echo "MacOS not supported yet..."
-   exit 1
+   echo "MacOS"
 else 
    echo "Unknown platform"
    exit 1
@@ -105,8 +104,35 @@ cat <<EOF > version.txt
 QEMU-3dfx-arch (Arch Linux build)
 =================================================
 Version $(echo $QEMUVERSION.r$(git rev-list --count HEAD).$(git rev-parse --short=7 HEAD))
-Built using GCC $(gcc --version | head -n 1 | cut -d '' -f 3)
+Built using GCC $(gcc --version | head -n 1 | awk '{print $3}')
 EOF
 echo "Signed version.txt"
+exit 0
+
+# macOS
+elif [ "$platform" = 'mac' ]; then
+   if [ -f ./bin/qemu-system-i386 ];
+   then echo 'QEMU found!'
+   else
+      echo "qemu-system-i386 not found!"
+      exit 1
+   fi
+QEMUVERSION=$(./bin/qemu-system-i386 --version | head -n 1 | awk '{print $4}')
+cat <<EOF > build-timestamp.txt 
+Built on $(date +"%H:%M:%S %B %d %Y")
+  $(brew list --versions binutils) 
+  $(brew list --versions git) 
+  $(brew list --versions gcc)
+EOF
+echo "Signed build-timestamp.txt"
+
+cat <<EOF > version.txt
+QEMU-3dfx-arch (macOS build)
+=================================================
+Version $(echo $QEMUVERSION.r$(git rev-list --count HEAD).$(git rev-parse --short=7 HEAD))
+Built using GCC $(gcc --version | head -n 1 | awk '{print $3}')
+EOF
+   echo "Signed version.txt"
+   exit 0
 fi
 exit 0
