Update sign_binary
sining x86_64 and aarch64 binary in macOS due to segmentation fault

diff --git a/scripts/sign_binary b/scripts/sign_binary
--- a/scripts/sign_binary
+++ b/scripts/sign_binary
@@ -111,28 +111,30 @@ exit 0
 
 # macOS
 elif [ "$platform" = 'mac' ]; then
-   if [ -f ./bin/qemu-system-i386 ];
-   then echo 'QEMU found!'
-   else
-      echo "qemu-system-i386 not found!"
-      exit 1
-   fi
-QEMUVERSION=$(./bin/qemu-system-i386 --version | head -n 1 | awk '{print $4}')
-cat <<EOF > build-timestamp.txt 
+   BINARIES=("qemu-system-i386" "qemu-system-x86_64" "qemu-system-aarch64")
+   for BINARY in "${BINARIES[@]}"; do
+      if [ -f ./bin/$BINARY ]; then
+         echo "$BINARY found!"
+      else
+         echo "$BINARY not found!"
+         exit 1
+      fi
+      QEMUVERSION=$(./bin/$BINARY --version | head -n 1 | awk '{print $4}')
+      cat <<EOF > build-timestamp.txt
 Built on $(date +"%H:%M:%S %B %d %Y")
-  $(brew list --versions binutils) 
-  $(brew list --versions git) 
+  $(brew list --versions binutils)
+  $(brew list --versions git)
   $(brew list --versions gcc)
 EOF
-echo "Signed build-timestamp.txt"
+      echo "Signed build-timestamp.txt"
 
-cat <<EOF > version.txt
+      cat <<EOF > version.txt
 QEMU-3dfx-arch (macOS build)
 =================================================
 Version $(echo $QEMUVERSION.r$(git rev-list --count HEAD).$(git rev-parse --short=7 HEAD))
 Built using GCC $(gcc --version | head -n 1 | awk '{print $3}')
 EOF
-   echo "Signed version.txt"
+      echo "Signed version.txt"
+   done
    exit 0
 fi
-exit 0
